"""Initial migration

Revision ID: 5a7506cb8036
Revises: be4cfb79dba9
Create Date: 2025-07-13 22:16:08.275629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7506cb8036'
down_revision = 'be4cfb79dba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
